version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bestor-sam-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-47kbu1pcfqna"
s3_prefix = "bestor-sam-test"
region = "us-east-1"
profile = "dev"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AwsSamPoc=\"arn:aws:iam::406205545357:role/AwsSamPoc\""
